### ISSUE TITLE
Calamari client package build failed for CentOS

### ISSUE THREAD

**Issue by ksingh7** [ceph/calamari#295] opened 2015-06-07 19:21 UTC
I have builded calamari server packages successfully for CentOS , next i was trying to build calamari client packages for CentOS but it failed with the error as

Full logs here : http://paste.ubuntu.com/11632381/

```bash
[INFO    ] Completed state [make rpm] at time 19:14:34.437209
local:
----------
          ID: rh_repackage_deps
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
     Started: 19:14:28.519342
    Duration: 3810.621 ms
     Changes:
----------
          ID: git_clone
    Function: git.latest
        Name: /git/calamari-clients
      Result: True
     Comment: Repository /git/calamari-clients cloned to /home/vagrant/clients
     Started: 19:14:32.399199
    Duration: 1877.558 ms
     Changes:
              ----------
              new:
                  /git/calamari-clients
              revision:
                  931ee5883cf52bb6a176634aabf8c41a628e84b8
----------
          ID: copyin_build_product
    Function: cmd.run
        Name: cp /git/calamari-clients*tar.gz /home/vagrant/clients
      Result: False
     Comment: Command "cp /git/calamari-clients*tar.gz /home/vagrant/clients" run
     Started: 19:14:34.279902
    Duration: 40.186 ms
     Changes:
              ----------
              pid:
                  2796
              retcode:
                  1
              stderr:
                  cp: cannot stat `/git/calamari-clients*tar.gz': No such file or directory
              stdout:
----------
          ID: build_calamari_clients
    Function: cmd.run
        Name: make rpm
      Result: False
     Comment: Command "make rpm" run
     Started: 19:14:34.323721
    Duration: 113.488 ms
     Changes:
              ----------
              pid:
                  2809
              retcode:
                  2
              stderr:
                  + umask 022
                  + cd /home/vagrant/clients/../rpmbuild/BUILD
                  + LANG=C
                  + export LANG
                  + unset DISPLAY
                  + echo prep
                  + exit 0
                  + umask 022
                  + cd /home/vagrant/clients/../rpmbuild/BUILD
                  + '[' /home/vagrant/rpmbuild/BUILDROOT/calamari-clients-1.2.2-32_g931ee58.el6.x86_64 '!=' / ']'
                  + rm -rf /home/vagrant/rpmbuild/BUILDROOT/calamari-clients-1.2.2-32_g931ee58.el6.x86_64
                  ++ dirname /home/vagrant/rpmbuild/BUILDROOT/calamari-clients-1.2.2-32_g931ee58.el6.x86_64
                  + mkdir -p /home/vagrant/rpmbuild/BUILDROOT
                  + mkdir /home/vagrant/rpmbuild/BUILDROOT/calamari-clients-1.2.2-32_g931ee58.el6.x86_64
                  + LANG=C
                  + export LANG
                  + unset DISPLAY
                  + echo install
                  + mkdir -p /home/vagrant/rpmbuild/BUILDROOT/calamari-clients-1.2.2-32_g931ee58.el6.x86_64
                  + cd /home/vagrant/rpmbuild/BUILDROOT/calamari-clients-1.2.2-32_g931ee58.el6.x86_64
                  + tar xfz /home/vagrant/clients/calamari-clients-build-output.tar.gz
                  tar (child): /home/vagrant/clients/calamari-clients-build-output.tar.gz: Cannot open: No such file or directory
                  tar (child): Error is not recoverable: exiting now
                  tar: Child returned status 2
                  tar: Error is not recoverable: exiting now
                  error: Bad exit status from /var/tmp/rpm-tmp.F6IpoI (%install)
                      Bad exit status from /var/tmp/rpm-tmp.F6IpoI (%install)
                  make: *** [rpm] Error 1
              stdout:
                  mkdir -p /home/vagrant/clients/../rpmbuild/{SPECS,RPMS,BUILDROOT}
                  cp clients.spec /home/vagrant/clients/../rpmbuild/SPECS
                  ( \
                  	cd /home/vagrant/clients/../rpmbuild; \
                  	rpmbuild -bb --define "_topdir /home/vagrant/clients/../rpmbuild" --define "version 1.2.2" --define "revision 32_g931ee58" --define "tarname /home/vagrant/clients/calamari-clients-build-output.tar.gz" SPECS/clients.spec; \
                  	)
                  Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.SAzPjb
                  prep
                  Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.F6IpoI
                  install


                  RPM build errors:
----------
          ID: copy_calamari_clients
    Function: cmd.run
        Name: cp rpmbuild/RPMS/x86_64/calamari-clients*.rpm /git
      Result: False
     Comment: One or more requisite failed: make_rpm.build_calamari_clients
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 2 (changed=3)
Failed:    3
------------
Total states run:     5
[vagrant@vagrant-centos64 ~]$

[vagrant@vagrant-centos64 ~]$ df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/sda1             7.3G  1.2G  5.8G  17% /
tmpfs                 246M   12K  246M   1% /dev/shm
git                   233G  215G   18G  93% /git
vagrant               233G  215G   18G  93% /vagrant
srv_salt              233G  215G   18G  93% /srv/salt
[vagrant@vagrant-centos64 ~]$
[vagrant@vagrant-centos64 ~]$ exit
logout
Connection to 127.0.0.1 closed.
teeri:centos-package ksingh$
teeri:centos-package ksingh$ cd ../..
teeri:calamari-clients ksingh$
teeri:calamari-clients ksingh$
teeri:calamari-clients ksingh$
teeri:calamari-clients ksingh$ ls -la
total 96
drwxr-xr-x  22 ksingh  staff   748 Jun  7 22:07 .
drwxr-xr-x   9 ksingh  staff   306 Jun  7 22:07 ..
drwxr-xr-x  12 ksingh  staff   408 Jun  7 22:07 .git
-rw-r--r--   1 ksingh  staff   175 Jun  7 22:07 .gitignore
-rw-r--r--   1 ksingh  staff  1646 Jun  7 22:07 COPYING
-rw-r--r--   1 ksingh  staff  1127 Jun  7 22:07 LICENSE.txt
-rw-r--r--   1 ksingh  staff  4569 Jun  7 22:07 Makefile
-rw-r--r--   1 ksingh  staff   910 Jun  7 22:07 Makefile.sub
-rw-r--r--   1 ksingh  staff   856 Jun  7 22:07 README.md
drwxr-xr-x  16 ksingh  staff   544 Jun  7 22:07 admin
-rw-r--r--   1 ksingh  staff  1398 Jun  7 22:07 bootstrap.md
-rw-r--r--   1 ksingh  staff  2222 Jun  7 22:07 calamari-clients.suse.spec
-rw-r--r--   1 ksingh  staff  1170 Jun  7 22:07 clients.spec
drwxr-xr-x  12 ksingh  staff   408 Jun  7 22:07 dashboard
drwxr-xr-x  10 ksingh  staff   340 Jun  7 22:07 debian
-rwxr-xr-x   1 ksingh  staff   874 Jun  7 22:07 get-versions.sh
drwxr-xr-x  14 ksingh  staff   476 Jun  7 22:07 login
drwxr-xr-x  18 ksingh  staff   612 Jun  7 22:07 manage
drwxr-xr-x  11 ksingh  staff   374 Jun  7 22:07 screenshots
-rw-r--r--   1 ksingh  staff   815 Jun  7 22:07 ui.build.instructions.md
drwxr-xr-x   9 ksingh  staff   306 Jun  7 22:07 utils
drwxr-xr-x  10 ksingh  staff   340 Jun  7 22:07 vagrant
teeri:calamari-clients ksingh$ cd ..
teeri:calamari-git ksingh$ ls -la
total 65136
drwxr-xr-x   9 ksingh  staff       306 Jun  7 22:07 .
drwxr-xr-x  10 ksingh  staff       340 Jun  7 22:03 ..
drwxr-xr-x  28 ksingh  staff       952 Jun  7 21:07 Diamond
drwxr-xr-x  33 ksingh  staff      1122 Jun  7 21:05 calamari
drwxr-xr-x  22 ksingh  staff       748 Jun  7 22:07 calamari-clients
-rw-r--r--   1 ksingh  staff   8256819 Jun  7 21:46 calamari-repo-el6.tar.gz
-rw-r--r--   1 ksingh  staff  24194260 Jun  7 21:46 calamari-server-1.3-rc_50_gd6e43c6.el6.x86_64.rpm
-rw-r--r--   1 ksingh  staff    595540 Jun  7 21:46 diamond-3.4.67-0.noarch.rpm
-rw-r--r--   1 ksingh  staff    297532 Jun  7 21:46 diamond-3.4.67-0.src.rpm
teeri:calamari-git ksingh$
```

**Comment by GregMeno** [comment] 2015-06-09 16:29
closing as this is basically a duplicate of #296

**Closed by GregMeno** 2015-06-09 16:29 UTC
