### ISSUE TITLE
Cthulhu doesn't work with Salt 2015.5.0

### ISSUE THREAD

**Issue by rimmington** [ceph/calamari#285] opened 2015-05-13 03:19 UTC
```
# calamari-common/calamari_common/salt_wrapper.py
from salt.loader import _create_loader
```

It looks like _create_loader is gone/moved in 2015.5.0, so `client_config` is defined as returning `None` and cthulhu promptly crashes.

Workaround is to use the `saltstack/salt2014-7` PPA.

**Comment by GregMeno** [comment] 2015-05-14 20:25
@rimmington Thank you for the report.

**Comment by alexm** [comment] 2015-05-15 11:55
I think that there's something else going on here: yesterday I installed calamari from scratch and it worked fine. When I got to the office today, it had started giving error 500 due to cthulhu not starting. What I'm wondering is how salt was updated since I'm using a private reposity and no newer salt versions were added there.

Shouldn't calamari have failed from the beginning if cthulhu can't start?

**Comment by alexm** [comment] 2015-05-15 12:51
I reinstalled calamari a couple of times now, and I understand why it worked the first time: starting from scratch the salt version installed is 0.17.5+ds-1 from the ubuntu mirrors. Even though **cthulhu isn't working**, older salt doesn't complain and calamari web UI works fine. So it seems that salt has become more sentitive to cthulhu not running on 2015.5.0, not the other way around.

By connecting the calamari master node with `ceph-deploy calamari connect ...` salt packages are upgraded to 2015.5.0+ds-1trusty1. Daemons are restarted, but calamari still works fine.

What happened in our case is that we restarted the calamari master this morning and it was then that calamari stopped working and showed server error 500.

In order to reproduce this scenario I removed all calamari packages and dependencies, removed also the `/etc/apt/sources.list.d/calamari-minion.list` (this is the important step to get an older version of salt) and did an `apt-get update` before reinstalling everything again.

**Comment by alexm** [comment] 2015-05-15 13:28
My workaround in #286 helps supervisord starting cthulhu again.

Hope that helps!

**Comment by GregMeno** [comment] 2015-05-20 17:36
@rimmington I have merged a fix from @alexm to master.
Would you please update and test?

**Comment by ksingh7** [comment] 2015-05-22 21:05
@alexm @GregMeno 

Doesn't works for me , i tried building fresh packages today , could you suggest something , to make this work.

[root@storage0111 calamari]# rpm -qa | grep -i salt
salt-2015.5.0-1.el6.noarch
salt-minion-2015.5.0-1.el6.noarch
salt-master-2015.5.0-1.el6.noarch
[root@storage0111 calamari]#
[root@storage0111 calamari]#
[root@storage0111 calamari]# supervisorctl status
carbon-cache   RUNNING    pid 540961, uptime 0:05:51
cthulhu        FATAL      Exited too quickly (process log may have details)
[root@storage0111 calamari]#
[root@storage0111 calamari]#
[root@storage0111 calamari]# tail -50f /var/log/calamari/calamari.log
    return self.hub.switch()
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat
2015-05-22 15:41:49,650 - ERROR - django.request Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/opt/calamari/venv/lib/python2.6/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/calamari/venv/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/calamari/venv/lib/python2.6/site-packages/calamari_web-0.1-py2.6.egg/calamari_web/views.py", line 38, in dashboard
    clusters = client.list_clusters()
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/core.py", line 260, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/core.py", line 245, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/core.py", line 217, in _process_response
    reply_event = bufchan.recv(timeout)
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/channel.py", line 267, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat
2015-05-22 15:54:41,040 - ERROR - django.request Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/opt/calamari/venv/lib/python2.6/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/calamari/venv/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/calamari/venv/lib/python2.6/site-packages/calamari_web-0.1-py2.6.egg/calamari_web/views.py", line 38, in dashboard
    clusters = client.list_clusters()
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/core.py", line 260, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/core.py", line 245, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/core.py", line 217, in _process_response
    reply_event = bufchan.recv(timeout)
  File "/opt/calamari/venv/lib/python2.6/site-packages/zerorpc/channel.py", line 267, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/opt/calamari/venv/lib/python2.6/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat

@alexm Your fix applied to /opt/calamari/venv/lib/python2.6/site-packages/calamari_common-0.1-py2.6.egg/calamari_common/salt_wrapper.py

![image](https://cloud.githubusercontent.com/assets/9701902/7779662/164b5aaa-00df-11e5-877d-7db23cb34159.png)

**Comment by GregMeno** [comment] 2015-05-22 21:41
@ksingh7 are the salt-master and salt-minions on the cluster nodes the same version?

**Comment by ksingh7** [comment] 2015-05-23 08:27
@GregMeno 
Yep they are same

[root@storage0111 calamari]# rpm -qa | grep -i salt
salt-2015.5.0-1.el6.noarch
salt-minion-2015.5.0-1.el6.noarch
salt-master-2015.5.0-1.el6.noarch
[root@storage0111 calamari]#

[root@storage0111 ~]# salt-master --version
salt-master 2015.5.0 (Lithium)
[root@storage0111 ~]# salt-minion --version
salt-minion 2015.5.0 (Lithium)
[root@storage0111 ~]#

Any help would be really appreciated.

**Comment by alexm** [comment] 2015-05-26 15:44
@ksingh7 try this and tell us if cthulhu-manager is reporting any messages:
```
supervisorctl stop cthulhu
/opt/calamari/venv/bin/cthulhu-manager
```
In my case, no message is displayed, meaning it works as expected.

**Comment by ksingh7** [comment] 2015-05-27 09:23
@alexm @GregMeno 

Do you know the reason why ``` supervisorctl start / stop cthulhu ``` command ( does not shows any output ) or even does not show prompt. However the service starts and stops with the command.


```bash
# supervisorctl status
carbon-cache   RUNNING    pid 540961, uptime 4 days, 10:28:45
cthulhu        STOPPED    May 27 10:20 AM
# supervisorctl start cthulhu


^CTraceback (most recent call last):
  File "/usr/bin/supervisorctl", line 6, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/supervisor/supervisorctl.py", line 598, in main
    c.onecmd(" ".join(options.args))
  File "/usr/lib/python2.6/site-packages/supervisor/supervisorctl.py", line 86, in onecmd
    return func(arg)
  File "/usr/lib/python2.6/site-packages/supervisor/supervisorctl.py", line 369, in do_start
    result = supervisor.startProcess(processname)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/site-packages/supervisor/options.py", line 1309, in request
    errcode, errmsg, headers = h.getreply()
  File "/usr/lib64/python2.6/httplib.py", line 1064, in getreply
    response = self._conn.getresponse()
  File "/usr/lib64/python2.6/httplib.py", line 990, in getresponse
    response.begin()
  File "/usr/lib64/python2.6/httplib.py", line 391, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.6/httplib.py", line 349, in _read_status
    line = self.fp.readline()
  File "/usr/lib64/python2.6/socket.py", line 433, in readline
    data = recv(1)
KeyboardInterrupt
#

# supervisorctl status
carbon-cache   RUNNING    pid 540961, uptime 4 days, 10:29:28
cthulhu        RUNNING    pid 2156075, uptime 0:00:22
#
```

**Comment by alexm** [comment] 2015-05-27 12:37
@ksingh7 That seems a problem with supervisord. Check the logs to find more information about what's going on. In my case it doesn't happen:

```
root@disk-host-2:~# supervisorctl stop cthulhu
cthulhu: stopped
root@disk-host-2:~# supervisorctl status
carbon-cache                     RUNNING    pid 144283, uptime 9 days, 2:38:57
cthulhu                          STOPPED    May 27 02:33 PM
root@disk-host-2:~# supervisorctl start cthulhu
cthulhu: started
```

**Comment by GregMeno** [comment] 2015-05-27 16:56
@ksingh7 weird that supervisorctl is not printing start stop messages. would you please tell us the version of supervisor you are running.

Also to see cthulhu run in the foreground you can do:
<pre>
(env)vagrant@localhost:~/calamari$ supervisorctl
calamari-frontend                RUNNING   pid 27007, uptime 0:00:04
carbon-cache                     RUNNING   pid 27006, uptime 0:00:04
cthulhu                          RUNNING   pid 27008, uptime 0:00:04
salt-master                      RUNNING   pid 27005, uptime 0:00:04
supervisor> fg cthulhu
Exiting foreground
supervisor>
</pre>

**Comment by ksingh7** [comment] 2015-06-22 21:56
@GregMeno @alexm 

I started fresh and not supervisorctl is responding correctly 

I am getting error in calamari dashboard , could you share some lovely hacks :)

```
2015-06-22 16:49:01,048 - metric_access - django.request No graphite data for ceph.cluster.9609b429-eee2-4e23-af31-28a24fcf5cbc.df.total_used
2015-06-22 16:49:01,049 - metric_access - django.request No graphite data for ceph.cluster.9609b429-eee2-4e23-af31-28a24fcf5cbc.df.total_space
2015-06-22 16:49:01,050 - metric_access - django.request No graphite data for ceph.cluster.9609b429-eee2-4e23-af31-28a24fcf5cbc.df.total_avail
2015-06-22 16:49:01,243 - ERROR - django.request Internal Server Error: /api/v1/cluster/9609b429-eee2-4e23-af31-28a24fcf5cbc/osd
```

![image](https://cloud.githubusercontent.com/assets/9701902/8294095/81d30900-1942-11e5-8d19-12915402cd66.png)

**Comment by joehandzik** [comment] 2015-06-22 22:01
I can't say for sure if I fixed any of this or not, but my PR (https://github.com/ceph/calamari/pull/299) addresses an issue with 2015.5.1. Basically, while putting static_loader in instead of _create_loader gets things to compile, they will not run correctly (static_loader returns a dict that previous versions didn't). You'll end up with a failure because an unrecognized method is being called (gen_functions doesn't exist in later versions of salt). Might be worth trying with my changes.

**Comment by ksingh7** [comment] 2015-06-23 19:15
@joehandzik  Thanks for answer.

I have applied your [fix](https://github.com/joehandzik/calamari/commit/d1fb4b794fcd820f90a8ddf7e0f5c651affd8302), by just replacing server_metadata.py with your new version file. But it didn't helped to fix this ```server error 500```.

Do you think this method of applying the fix is wrong , so should i recompile calamari server packages. ?

**Comment by joehandzik** [comment] 2015-06-23 19:19
I would think that what you did would be sufficient, but one of the Red Hat developers would probably know better.

I'm taking a look at the code now to see if there's something that stands out. The error is pretty cut and dry from what I can see, it says that your heartbeat isn't returning within the 10 second window. I'll update your bug report if I can think of something smart for you to try.

**Comment by ksingh7** [comment] 2015-06-23 19:25
@joehandzik  That's so kind of you :+1: 

I have created a new #309 for this problem.
The current thread  #285 is of a different problem "Cthulhu doesn't work with Salt 2015.5.0" 

So if we able to fix this , others can find the solution as well on the correct #309 

Follow up on #309

**Comment by GregMeno** [comment] 2015-06-23 21:25
I just merged https://github.com/ceph/calamari/pull/299
Any objections to closing this issue?

**Comment by joehandzik** [comment] 2015-06-23 21:27
It should probably be closed, yes. @ksingh7's issue can be discussed further on #309.

**Closed** 2015-06-23 21:37 UTC

**Comment by renhongchang** [comment] 2015-07-11 10:34
i use salt-2014.7.6 to solve this problem and calamari works fine.

https://github.com/saltstack/salt/releases/download/v2014.7.6/salt-2014.7.6.tar.gz

**Comment by ksingh7** [comment] 2015-07-11 12:18
@renhongchang is your ceph cluster nodes are connected to calamari as well. Is everything fine from the dashboard.
